version: '3'

services:
  redis:
    image: redis:3.2

  opennotifyapi:
    image: open-notify-api
    depends_on:
      - redis
    environment:
      - REDISTOGO_URL=redis://redis:6379
    volumes:
      - "./:/Open-Notify-API/"
    ports:
      - "5000:5000"